### ISSUE TITLE
Empty space after ?> causes exception

### ISSUE THREAD

**Issue by hurricup** [hurricup/Perl5-IDEA#224]

**Comment by hurricup** [comment]
No idea what is going on:
```
[  15780]  ERROR - enapi.editor.impl.DocumentImpl - Wrong end: 8; document length=7; start=7 
java.lang.IllegalArgumentException: Wrong end: 8; document length=7; start=7
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:44)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:37)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.<init>(RangeHighlighterImpl.java:74)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighterAndChangeAttributes(MarkupModelImpl.java:125)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighter(MarkupModelImpl.java:175)
	at idea.plugin.psiviewer.view.EditorPsiElementHighlighter.apply(EditorPsiElementHighlighter.java:80)
	at idea.plugin.psiviewer.view.EditorPsiElementHighlighter.access$000(EditorPsiElementHighlighter.java:24)
	at idea.plugin.psiviewer.view.EditorPsiElementHighlighter$1.run(EditorPsiElementHighlighter.java:45)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:867)
	at idea.plugin.psiviewer.view.EditorPsiElementHighlighter.highlightElement(EditorPsiElementHighlighter.java:41)
	at idea.plugin.psiviewer.view.PsiViewerPanel.applyHighlighting(PsiViewerPanel.java:211)
	at idea.plugin.psiviewer.view.PsiViewerPanel.setSelectedElement(PsiViewerPanel.java:242)
	at idea.plugin.psiviewer.view.PsiViewerPanel.selectElementAtCaret(PsiViewerPanel.java:337)
	at idea.plugin.psiviewer.view.PsiViewerPanel.selectElementAtCaret(PsiViewerPanel.java:312)
	at idea.plugin.psiviewer.controller.project.EditorListener.caretPositionChanged(EditorListener.java:144)
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
	at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
	at com.sun.proxy.$Proxy29.caretPositionChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.CaretModelImpl.fireCaretPositionChanged(CaretModelImpl.java:504)
	at com.intellij.openapi.editor.impl.CaretImpl.a(CaretImpl.java:580)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToLogicalPosition(CaretImpl.java:720)
	at com.intellij.openapi.editor.impl.CaretImpl.updateCaretPosition(CaretImpl.java:872)
	at com.intellij.openapi.editor.impl.CaretModelImpl$2.run(CaretModelImpl.java:89)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:417)
	at com.intellij.openapi.editor.impl.CaretModelImpl.documentChanged(CaretModelImpl.java:85)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:795)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:731)
	at com.intellij.openapi.editor.impl.DocumentImpl.deleteString(DocumentImpl.java:528)
	at com.intellij.openapi.editor.actions.BackspaceAction.a(BackspaceAction.java:92)
	at com.intellij.openapi.editor.actions.BackspaceAction.access$100(BackspaceAction.java:36)
	at com.intellij.openapi.editor.actions.BackspaceAction$Handler.executeWriteAction(BackspaceAction.java:55)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:56)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:222)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.handleBackspace(BackspaceHandler.java:105)
	at com.intellij.codeInsight.editorActions.BackspaceHandler.executeWriteAction(BackspaceHandler.java:61)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:56)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:203)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:342)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:422)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:333)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:324)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:200)
	at com.intellij.codeInsight.lookup.impl.BackspaceHandler.doExecute(BackspaceHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$4.perform(EditorActionHandler.java:217)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:214)
	at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:593)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:644)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:483)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
[  15786]  ERROR - enapi.editor.impl.DocumentImpl - IntelliJ IDEA 14.1.4  Build #IU-141.1532.4 
[  15787]  ERROR - enapi.editor.impl.DocumentImpl - JDK: 1.7.0_60-ea 
[  15787]  ERROR - enapi.editor.impl.DocumentImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
[  15787]  ERROR - enapi.editor.impl.DocumentImpl - Vendor: Oracle Corporation 
[  15787]  ERROR - enapi.editor.impl.DocumentImpl - OS: Windows 7 
[  15787]  ERROR - enapi.editor.impl.DocumentImpl - Last Action: EditorBackSpace 
[  15787]  ERROR - enapi.editor.impl.DocumentImpl - Current Command: Backspace 
[  15818]  ERROR - .psi.impl.DocumentCommitThread - IdeaLoggingEvent[message=commitDocument left PSI inconsistent: HtmlFile:test.thtml; file len=5; doc len=7; doc.getText() == file.getText(): false, throwable=java.lang.Throwable
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:497)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:98)
	at com.intellij.psi.impl.DocumentCommitProcessor.a(DocumentCommitProcessor.java:236)
	at com.intellij.psi.impl.DocumentCommitProcessor.access$000(DocumentCommitProcessor.java:50)
	at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:138)
	at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:126)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommitInWriteAction(PsiDocumentManagerBase.java:322)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.finishCommitInWriteAction(PsiDocumentManagerImpl.java:133)
	at com.intellij.psi.impl.PsiDocumentManagerBase$3.run(PsiDocumentManagerBase.java:292)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommit(PsiDocumentManagerBase.java:289)
	at com.intellij.psi.impl.DocumentCommitThread$5.run(DocumentCommitThread.java:521)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
] 
[  15824]  ERROR - .psi.impl.DocumentCommitThread - PSI is broken beyond repair in: HtmlFile:test.thtml 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.psi.impl.DocumentCommitProcessor.a(DocumentCommitProcessor.java:250)
	at com.intellij.psi.impl.DocumentCommitProcessor.access$000(DocumentCommitProcessor.java:50)
	at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:138)
	at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:126)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommitInWriteAction(PsiDocumentManagerBase.java:322)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.finishCommitInWriteAction(PsiDocumentManagerImpl.java:133)
	at com.intellij.psi.impl.PsiDocumentManagerBase$3.run(PsiDocumentManagerBase.java:292)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommit(PsiDocumentManagerBase.java:289)
	at com.intellij.psi.impl.DocumentCommitThread$5.run(DocumentCommitThread.java:521)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
[  15824]  ERROR - .psi.impl.DocumentCommitThread - IntelliJ IDEA 14.1.4  Build #IU-141.1532.4 
[  15824]  ERROR - .psi.impl.DocumentCommitThread - JDK: 1.7.0_60-ea 
[  15824]  ERROR - .psi.impl.DocumentCommitThread - VM: Java HotSpot(TM) 64-Bit Server VM 
[  15824]  ERROR - .psi.impl.DocumentCommitThread - Vendor: Oracle Corporation 
[  15824]  ERROR - .psi.impl.DocumentCommitThread - OS: Windows 7 
[  15824]  ERROR - .psi.impl.DocumentCommitThread - Last Action: EditorBackSpace 
```
Asked JB: https://devnet.jetbrains.com/message/5548624#5548624
