### ISSUE TITLE
CamelCade breaks several refactorings in PHPStorm 8

### ISSUE THREAD

**Issue by sGy1980de** [hurricup/Perl5-IDEA#236]
Hi, 

using PHPStorm 8.0.3 with CamelCade (tested 0.33 / 0.34) breaks severeal refactorings in all Projects. You can't move, copy or delete files. All PHP refactorings are also not available. Unfortunately the event console says nothing about that.

Here some messages from the log file, perhaps they are helpful?!?
```
2015-07-23 14:55:46,071 [ 310439]  ERROR - llij.ide.plugins.PluginManager - PhpStorm 8.0.3  Build #PS-139.1348 
2015-07-23 14:55:46,071 [ 310439]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_51 
2015-07-23 14:55:46,071 [ 310439]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-07-23 14:55:46,071 [ 310439]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
2015-07-23 14:55:46,071 [ 310439]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2015-07-23 14:55:46,071 [ 310439]  ERROR - llij.ide.plugins.PluginManager - Last Action: RenameElement 
2015-07-23 14:55:46,209 [ 310577]  ERROR - llij.ide.plugins.PluginManager - com/intellij/psi/PsiPackage 
java.lang.NoClassDefFoundError: com/intellij/psi/PsiPackage
	at com.perl5.lang.perl.idea.PerlElementDescriptionProvider.getElementDescription(PerlElementDescriptionProvider.java:53)
	at com.intellij.psi.ElementDescriptionUtil.getElementDescription(ElementDescriptionUtil.java:31)
	at com.intellij.usageView.UsageViewUtil.getType(UsageViewUtil.java:68)
	at com.intellij.refactoring.rename.RenameDialog.getFullName(RenameDialog.java:142)
	at com.intellij.refactoring.rename.RenameDialog.getLabelText(RenameDialog.java:114)
	at com.intellij.refactoring.rename.RenameDialog.<init>(RenameDialog.java:87)
	at com.intellij.refactoring.rename.RenamePsiElementProcessor.createRenameDialog(RenamePsiElementProcessor.java:55)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:159)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.rename(PsiElementRenameHandler.java:151)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.invoke(PsiElementRenameHandler.java:104)
	at com.intellij.refactoring.rename.PsiElementRenameHandler.invoke(PsiElementRenameHandler.java:67)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:122)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:614)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:663)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:513)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:546)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by sGy1980de** [comment]
Appendix: I also tested with JVM 1.7 -> same issue.

**Comment by hurricup** [comment]
Sorry, seems it's my bad. Used some Java-specific classes in IDEA and they do exists only in IDEA. 
Created an issue to get rid of them. And will mark next build to be compatible only with IDEA.
You may watch https://github.com/hurricup/Perl5-IDEA/issues/265 to see when situation will change.
