### ISSUE TITLE
Exception on attempt of inplace renaming for variables and heredocs

### ISSUE THREAD

**Issue by hurricup** [hurricup/Perl5-IDEA#290]
If put caret not in variable/heredoc name, but before sigil or <<, attempting to refactor causes:
```
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.a(InplaceRefactoring.java:728)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.buildTemplateAndStart(InplaceRefactoring.java:273)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.buildTemplateAndStart(VariableInplaceRenamer.java:121)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.performInplaceRefactoring(InplaceRefactoring.java:213)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.performInplaceRename(VariableInplaceRenamer.java:94)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenameHandler$1.pass(MemberInplaceRenameHandler.java:69)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenameHandler$1.pass(MemberInplaceRenameHandler.java:65)
	at com.intellij.refactoring.rename.RenamePsiElementProcessor.substituteElementToRename(RenamePsiElementProcessor.java:189)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenameHandler.doRename(MemberInplaceRenameHandler.java:65)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenameHandler.invoke(VariableInplaceRenameHandler.java:90)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:122)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:593)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:644)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:483)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
[  26809]  ERROR - inplace.VariableInplaceRenamer - IntelliJ IDEA 14.1.4  Build #IU-141.1532.4 
[  26810]  ERROR - inplace.VariableInplaceRenamer - JDK: 1.7.0_60-ea 
[  26810]  ERROR - inplace.VariableInplaceRenamer - VM: Java HotSpot(TM) 64-Bit Server VM 
[  26810]  ERROR - inplace.VariableInplaceRenamer - Vendor: Oracle Corporation 
[  26810]  ERROR - inplace.VariableInplaceRenamer - OS: Windows 7 
[  26810]  ERROR - inplace.VariableInplaceRenamer - Last Action: RenameElement 
[  26811]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.buildTemplateAndStart(InplaceRefactoring.java:287)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.buildTemplateAndStart(VariableInplaceRenamer.java:121)
	at com.intellij.refactoring.rename.inplace.InplaceRefactoring.performInplaceRefactoring(InplaceRefactoring.java:213)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenamer.performInplaceRename(VariableInplaceRenamer.java:94)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenameHandler$1.pass(MemberInplaceRenameHandler.java:69)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenameHandler$1.pass(MemberInplaceRenameHandler.java:65)
	at com.intellij.refactoring.rename.RenamePsiElementProcessor.substituteElementToRename(RenamePsiElementProcessor.java:189)
	at com.intellij.refactoring.rename.inplace.MemberInplaceRenameHandler.doRename(MemberInplaceRenameHandler.java:65)
	at com.intellij.refactoring.rename.inplace.VariableInplaceRenameHandler.invoke(VariableInplaceRenameHandler.java:90)
	at com.intellij.refactoring.actions.BaseRefactoringAction.actionPerformed(BaseRefactoringAction.java:122)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:593)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:644)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:483)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
[  26813]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 14.1.4  Build #IU-141.1532.4 
[  26813]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.7.0_60-ea 
[  26813]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
[  26813]  ERROR - llij.ide.plugins.PluginManager - Vendor: Oracle Corporation 
[  26814]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 7 
[  26814]  ERROR - llij.ide.plugins.PluginManager - Last Action: RenameElement 
```
Anyway, rename refactoring needs review.

**Comment by hurricup** [comment]
Correct references will fix this. Here-docs already fixed, vars on the way.
