### ISSUE TITLE
cant select perl5 interpreter

### ISSUE THREAD

**Issue by tcetveli** [hurricup/Perl5-IDEA#484]
nothing comes up when i try to add perl5 interpreter in the project structure. using idea 14 on debian 7

here is the console output

```
[   7390]   WARN - .ExternalResourceManagerExImpl - Cannot find standard resource. filename:/META-INF/tapestry_5_0_0.xsd class=class com.intellij.javaee.ResourceRegistrarImpl, classLoader:null 
[  22718]  ERROR - api.util.objectTree.ObjectNode - com.intellij.execution.process.ProcessOutput.getStdoutLines(Z)Ljava/util/List; 
java.lang.NoSuchMethodError: com.intellij.execution.process.ProcessOutput.getStdoutLines(Z)Ljava/util/List;
        at com.perl5.lang.perl.idea.sdk.PerlSdkType.getDataFromProgram(PerlSdkType.java:219)
        at com.perl5.lang.perl.idea.sdk.PerlSdkType.getPathFromPerl(PerlSdkType.java:202)
        at com.perl5.lang.perl.idea.sdk.PerlSdkType.suggestHomePath(PerlSdkType.java:109)
        at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.getSuggestedSdkRoot(SdkConfigurationUtil.java:303)
        at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:284)
        at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:275)
        at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel$3.actionPerformed(ProjectSdksModel.java:257)
        at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:739)
        at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1343)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:651)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.access$2600(FocusManagerImpl.java:60)
        at com.intellij.openapi.wm.impl.FocusManagerImpl$7.run(FocusManagerImpl.java:485)
        at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2108)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:476)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:59)
        at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1349)
        at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:153)
        at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:299)
        at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:47)
        at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
        at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:125)
        at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:102)
        at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:146)
        at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:102)
        at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:132)
        at com.intellij.openapi.util.Disposer.dispose(Disposer.java:108)
        at com.intellij.ui.popup.AbstractPopup.cancel(AbstractPopup.java:665)
        at com.intellij.ui.popup.WizardPopup.cancel(WizardPopup.java:247)
        at com.intellij.ui.popup.AbstractPopup.cancel(AbstractPopup.java:600)
        at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1288)
        at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:153)
        at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:299)
        at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:260)
        at com.intellij.ui.popup.list.ListPopupImpl.a(ListPopupImpl.java:416)
        at com.intellij.ui.popup.list.ListPopupImpl.a(ListPopupImpl.java:376)
        at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:334)
        at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:464)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
        at java.awt.Component.processMouseEvent(Component.java:6516)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
        at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:519)
        at java.awt.Component.processEvent(Component.java:6281)
        at java.awt.Container.processEvent(Container.java:2229)
        at java.awt.Component.dispatchEventImpl(Component.java:4872)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.awt.EventQueue$4.run(EventQueue.java:718)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
        at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
        at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
        at java.awt.Dialog.show(Dialog.java:1082)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:779)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:464)
        at com.intellij.openapi.ui.DialogWrapper.showAndGetOk(DialogWrapper.java:1569)
        at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1536)
        at com.intellij.ide.actions.ShowStructureSettingsAction.showDialog(ShowStructureSettingsAction.java:52)
        at com.intellij.ide.actions.ShowStructureSettingsAction.actionPerformed(ShowStructureSettingsAction.java:47)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:266)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:926)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:236)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:105)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
        at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
        at java.awt.Component.processMouseEvent(Component.java:6516)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
        at java.awt.Component.processEvent(Component.java:6281)
        at java.awt.Container.processEvent(Container.java:2229)
        at java.awt.Component.dispatchEventImpl(Component.java:4872)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.awt.EventQueue$4.run(EventQueue.java:718)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
        at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
[  22725]  ERROR - api.util.objectTree.ObjectNode - IntelliJ IDEA 14.0.4  Build #IU-139.1603.1 
[  22726]  ERROR - api.util.objectTree.ObjectNode - JDK: 1.7.0_79 
[  22726]  ERROR - api.util.objectTree.ObjectNode - VM: OpenJDK 64-Bit Server VM 
[  22726]  ERROR - api.util.objectTree.ObjectNode - Vendor: Oracle Corporation 
[  22726]  ERROR - api.util.objectTree.ObjectNode - OS: Linux
```

**Comment by hurricup** [comment]
Current version of IU is 141.2735, try to update your IDEA and let me know if problem persists.
Seems I need to rise a version requirement just a bit.

**Comment by hurricup** [comment]
I've updated source to use more legacy version of method in question, you may fetch current dev build, it should work fine: http://evstigneev.com/camelcade.jar

**Comment by halfo** [comment]
Hi, I'm also facing similar problem. And the [link to latest dev build](http://evstigneev.com/camelcade.jar) redirects to [this](http://evstigneev.com/index.shtml) page.

**Comment by hurricup** [comment]
What os, what java, what product? what are you doing and what is going on?
Link to the last dev buld may be found on twitter: https://twitter.com/CamelcadeIDE
I'll remove old link, thank you.

**Comment by halfo** [comment]
OS: Ubuntu 14.04
Java: Oracle Java 8
Product: Intellij Idea Community Edition 2016

I was following [these](https://github.com/hurricup/Perl5-IDEA/wiki/Getting-started:-IntelliJ-IDEA) steps.

* I added Perl Interpreter in platform SDK.
![screenshot from 2016-04-06 16 13 21](https://cloud.githubusercontent.com/assets/2076914/14315076/088119b6-fc1d-11e5-934b-975c94717de4.png)
* Then I set Perl as my Project SDK.
* I added a new module, chose "Perl Module". But there was no libraries under it.
![screenshot from 2016-04-06 16 13 02](https://cloud.githubusercontent.com/assets/2076914/14315169/81c81f7c-fc1d-11e5-8313-76b268c88471.png)
* No file/folder is generated.
![screenshot from 2016-04-06 16 14 10](https://cloud.githubusercontent.com/assets/2076914/14315238/cfa83114-fc1d-11e5-9e2a-b27ae7ee9630.png)
* And finally, I got this.
![screenshot from 2016-04-06 16 14 37](https://cloud.githubusercontent.com/assets/2076914/14315276/0e59b4f0-fc1e-11e5-8f6e-185d62e4d76f.png)

**Comment by hurricup** [comment]
First: This is not related to bug described above.

Second: according to your screenshots, everything works as intended. No files or directoreis should be created automatically. Project set up correctly: you have your project and sdk with sdk libs. 

Libraries in module settings are for marking your own project library directory. If you'll create hello/lib and put packages in there, you'll need to mark lib dir as libraries to make them resolvable.
