### ISSUE TITLE
Unexpected termination offset error in PodLexerAdapter using IDEA 16 CE preview

### ISSUE THREAD

**Issue by clignos-bbn** [hurricup/Perl5-IDEA#901]
I am using Intellij IDEA CE 16 preview (build IC-145.184.1) and after installing Camelcade version 1.342 I get the following error in the Event log:
```
IllegalStateException
           Error while indexing /home/clignos/perl5/perlbrew/perls/perl-5.20.3/lib/5.20.3/pod/perlsource.pod
           To reindex this file IDEA has to be restarted: Unexpected termination offset for lexer com.perl5.lang.pod.lexer.PodLexerAdapter@226f8b52
```

The full traceback from stderr is:
```
[   7151]  ERROR - napi.project.CacheUpdateRunner - Error while indexing /home/clignos/perl5/perlbrew/perls/perl-5.20.3/lib/5.20.3/pod/perlsource.pod
To reindex this file IDEA has to be restarted
java.lang.IllegalStateException: Unexpected termination offset for lexer com.perl5.lang.pod.lexer.PodLexerAdapter@15bbc5a2
        at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.doSetText(LexerEditorHighlighter.java:333)
        at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:302)
        at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:179)
        at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:156)
        at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:108)
        at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:100)
        at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
        at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1831)
        at com.intellij.util.indexing.FileBasedIndexImpl$23.run(FileBasedIndexImpl.java:1760)
        at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:510)
        at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1718)
        at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1703)
        at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:108)
        at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
        at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:226)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
        at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:246)
        at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:443)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
        at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:240)
        at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Using the same version of Camelcade with the stable IDEA 15 CE release doesn't appear to cause this exception.

**Comment by hurricup** [comment]
Could you please attach file in question?

**Comment by clignos-bbn** [comment]
I had to change add a .txt extension to upload, but here it is:
[perlsource.pod.txt](https://github.com/hurricup/Perl5-IDEA/files/165679/perlsource.pod.txt)

**Comment by hurricup** [comment]
You may use current build http://evstigneev.com/IDEA-Perl5-1.343.zip
Should work just fine. Thanks for report.

**Comment by clignos-bbn** [comment]
Thanks, just tested with that build and can confirm it's fixed. Thank you for the quick turnaround!
